# Generated by Django 3.2.8 on 2021-10-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='url_name',
            field=models.CharField(default='url', max_length=12, verbose_name='имя в URL'),
            preserve_default=False,
        ),
    ]
